"""Régénère LegalTerms/ (Markdown et PDF, FR / EN) depuis le texte publié par le site.

La source unique des conditions et de la politique du bot est
`lib/shared/bot-legal-content.ts` du dépôt AppBlueGenji, rendue sur
/terms-of-service-bot et /privacy-policy-bot. Ce script n'en est qu'une mise en
page : on ne corrige jamais un fichier de LegalTerms/ à la main.

1. Dans AppBlueGenji, exporter le contenu en JSON (bloc à coller tel quel,
   la fin du heredoc devant rester en début de ligne) :

cat > __dump.ts <<'TS'
import { TERMS_OF_SERVICE, PRIVACY_POLICY, HEBERGEUR_HREF } from "@/lib/shared/bot-legal-content";
import { writeFileSync } from "node:fs";
writeFileSync(process.argv[2], JSON.stringify({ TERMS_OF_SERVICE, PRIVACY_POLICY, HEBERGEUR_HREF }));
TS
npx tsx __dump.ts /chemin/legal.json && rm __dump.ts

2. Ici :  python scripts/generate-legal-terms.py /chemin/legal.json
   (dépend de `reportlab` ; polices Arial par défaut, `LEGAL_FONT_DIR` pour
   désigner un dossier contenant arial.ttf, arialbd.ttf et ariali.ttf).
"""
import json, re, sys, os
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.fonts import addMapping
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, ListFlowable, ListItem
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from xml.sax.saxutils import escape

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE = "https://bluegenji-esport.fr"
data = json.load(open(sys.argv[1], encoding="utf-8"))
HOST = data["HEBERGEUR_HREF"]
out = sys.argv[2] if len(sys.argv) > 2 else os.path.join(ROOT, "LegalTerms")
os.makedirs(out, exist_ok=True)

def absu(u): return SITE + u if u.startswith("/") else u
LINK = re.compile(r"\[([^\]]+)\]\(([^)]+)\)")
def md_inline(t): return LINK.sub(lambda m: f"[{m.group(1)}]({absu(m.group(2))})", t)
def pdf_inline(t):
    parts, pos = [], 0
    for m in LINK.finditer(t):
        parts.append(("t", t[pos:m.start()])); parts.append(("l", m.group(1), absu(m.group(2)))); pos = m.end()
    parts.append(("t", t[pos:]))
    def fmt(s): return re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", escape(s.replace("`", "")))
    return "".join(fmt(p[1]) if p[0] == "t" else f'<link href="{escape(p[2])}" color="#1a6fb0"><u>{fmt(p[1])}</u></link>' for p in parts)

DOCS = [
  ("TERMS_OF_SERVICE", "fr", "ConditionsUtilisation", "/terms-of-service-bot", "*For the English version, see [TermsOfServices.md](TermsOfServices.md).*"),
  ("TERMS_OF_SERVICE", "en", "TermsOfServices", "/terms-of-service-bot", "*La version française se trouve dans [ConditionsUtilisation.md](ConditionsUtilisation.md).*"),
  ("PRIVACY_POLICY", "fr", "Politique de confidentialité", "/privacy-policy-bot", "*For the English version, see [PolicyPrivacy.md](PolicyPrivacy.md).*"),
  ("PRIVACY_POLICY", "en", "PolicyPrivacy", "/privacy-policy-bot", "*La version française se trouve dans [Politique de confidentialité.md](Politique%20de%20confidentialit%C3%A9.md).*"),
]
NOTE = {
  "fr": "Copie du texte publié sur [{u}]({u}), **qui fait foi** en cas de divergence. Ne modifiez pas ce fichier à la main : il est régénéré depuis le site (`lib/shared/bot-legal-content.ts` d'AppBlueGenji).",
  "en": "Copy of the text published at [{u}]({u}), **which prevails** in case of any discrepancy. Do not edit this file by hand: it is regenerated from the website (`lib/shared/bot-legal-content.ts` in AppBlueGenji).",
}
PDFNAME = {"ConditionsUtilisation": "ConditionsUtilisation.pdf", "TermsOfServices": "TermsOfServices.pdf",
           "Politique de confidentialité": "PolitiqueConfidentialite.pdf", "PolicyPrivacy": "PolicyPrivacy.pdf"}

FONTS = os.environ.get("LEGAL_FONT_DIR", "C:/Windows/Fonts")
pdfmetrics.registerFont(TTFont("Arial", os.path.join(FONTS, "arial.ttf")))
pdfmetrics.registerFont(TTFont("Arial-Bold", os.path.join(FONTS, "arialbd.ttf")))
pdfmetrics.registerFont(TTFont("Arial-Italic", os.path.join(FONTS, "ariali.ttf")))
addMapping("Arial", 0, 0, "Arial"); addMapping("Arial", 1, 0, "Arial-Bold"); addMapping("Arial", 0, 1, "Arial-Italic"); addMapping("Arial", 1, 1, "Arial-Bold")
ss = getSampleStyleSheet()
body = ParagraphStyle("b", parent=ss["BodyText"], fontName="Arial", fontSize=10, leading=14, spaceAfter=6)
h1 = ParagraphStyle("h1", parent=ss["Title"], fontName="Arial-Bold", fontSize=20, leading=24)
h2 = ParagraphStyle("h2", parent=ss["Heading2"], fontName="Arial-Bold", fontSize=13, spaceBefore=10)
h3 = ParagraphStyle("h3", parent=ss["Heading3"], fontName="Arial-Bold", fontSize=11)
small = ParagraphStyle("s", parent=body, fontName="Arial-Italic", fontSize=9, textColor="#555555")

for key, lang, name, path, xref in DOCS:
    d = data[key][lang]; url = SITE + path; title = d["title"].replace("\n", " ")
    sep = " :" if lang == "fr" else ":"
    lines = [xref, "", f"# {title} — BlueGenji Bot", "", f"**{d['lastUpdatedLabel']}**{sep} {d['lastUpdated']}", "",
             "> " + md_inline(NOTE[lang].format(u=url)), "", md_inline(d["intro"]), ""]
    story = [Paragraph(escape(title) + " — BlueGenji Bot", h1),
             Paragraph(f"<b>{escape(d['lastUpdatedLabel'])}</b>{sep} {escape(d['lastUpdated'])}", body),
             Paragraph(pdf_inline(NOTE[lang].format(u=url)), small), Spacer(1, 6), Paragraph(pdf_inline(d["intro"]), body)]
    for s in d["sections"]:
        lines += ["---", "", f"## {s['num']}. {s['title']}", ""]
        story.append(Paragraph(f"{escape(s['num'])}. {escape(s['title'])}", h2))
        for b in s["blocks"]:
            if b["kind"] == "p":
                lines += [md_inline(b["text"]), ""]; story.append(Paragraph(pdf_inline(b["text"]), body))
            elif b["kind"] == "subhead":
                lines += [f"### {b['text']}", ""]; story.append(Paragraph(pdf_inline(b["text"]), h3))
            else:
                lines += [f"- {md_inline(i)}" for i in b["items"]] + [""]
                story.append(ListFlowable([ListItem(Paragraph(pdf_inline(i), body), leftIndent=12) for i in b["items"]],
                                          bulletType="bullet", start="•", leftIndent=12))
    h = d["hosting"]; hl = f"[{h['linkLabel'].rstrip(' →')}]({SITE + HOST})"
    lines += ["---", "", f"## {h['title']}", "", md_inline(h["text"]), "", hl, ""]
    story += [Paragraph(escape(h["title"]), h2), Paragraph(pdf_inline(h["text"]), body), Paragraph(pdf_inline(hl), body)]
    with open(os.path.join(out, name + ".md"), "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines).rstrip() + "\n")
    SimpleDocTemplate(os.path.join(out, PDFNAME[name]), pagesize=A4, title=f"{title} — BlueGenji Bot", author="BlueGenji Esport",
                      leftMargin=50, rightMargin=50, topMargin=50, bottomMargin=50, invariant=1).build(story)
print("LegalTerms régénéré dans", out)
